---
AWSTemplateFormatVersion: 2010-09-09
Description: Business Usecase- CF will use Packer AMI , provision EC2 and S3 buckets which are needed for application deployment 

Parameters:
  LatestImageId:
    Description: EC2 instance type..Provide base AMI or Packer AMI reference
    Type : AWS::SSM::Parameter::Value<String>
    Default: '/charter/tomcat-ami-id'
  IamInstanceProfile:
    Description:  IamInstanceProfile Name
    Type: String
    Default: ec2_s3_role
  InstanceType:
    Description:  EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small 
      - t2.medium	  
  AvailabilityZones:
    Description: EC2 Availability Zone
    Type: String
    Default: us-east-1d
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d	  
  KeyName:
    Description: Provide Existing keypair name.
    Type: AWS::EC2::KeyPair::KeyName
    Default: Dec-2019
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-04fb5ff8ee870bbae

  BucketName:
    Description: The Name and Tag to be given to the bucket. Should start with digitalx-
    Type: String
    Default: "charter-app-deployment"

  Retention:
    Description: The Retention to be given to the versions of each object on the bucket
    Default: 30
    Type: String

   
Resources:

#Create Shared S3 Bucket
  S3BucketTemplate:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: !Ref BucketName
            NoncurrentVersionExpirationInDays: !Ref Retention
            Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${BucketName}-bucket
        - Key: Resource
          Value: 's3-bucket'
  TestEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: subnet-fe101ad0
      SecurityGroupIds:
        - !Ref SecurityGroups
      ImageId: !Ref LatestImageId
      IamInstanceProfile: !Ref IamInstanceProfile
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZones
      KeyName: !Ref KeyName
      Tags:
        -
          Key: Name
          Value: Charter-POC-Instances
Outputs:

  S3BucketName:
    Description: Output for the s3 bucket
    Value: !Ref S3BucketTemplate
