AWSTemplateFormatVersion: "2010-09-09"  
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0080e4c5bc078760e
      KeyName: packer-infy-key
      SecurityGroupIds:
        - sg-0bee687735f5ada3c
      SubnetId: subnet-4db9b163
      Tags:
        -
          Key: Name
          Value: cf-stack-webserver
