AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample: Create
  an Amazon EC2 instance running the base Amazon Linux AMI. This example creates an EC2 security
  group for the instance to give you SSH access.
Parameters:
  KeyName:
    Description: Key Pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VPC:
    Type: 'AWS::EC2::VPC'
    ConstraintDescription: must be the name of an existing VPC.
    Properties:
      CidrBlock: 172.31.0.0/16
      EnableDnsHostnames: true
  Subnet:
    Type: 'AWS::EC2::Subnet'
    ConstraintDescription: must be the name of an existing Subnet.
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 172.31.80.0/20
      AvailabilityZone: us-east-1c
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    ConstraintDescription: must be a valid EC2 instance type.
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SourceSecurityGroupId: sg-0bee687735f5ada3c	  
      KeyName: !Ref KeyName
      ImageId: amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2 
      VpcId: !Ref VPC
      SubnetId: !Ref Subnet
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp
