AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Created AWS CF template in .yaml format for spinning up an EC2 instance with linux base image and take either t2.nano or t2.small type instance. Hardcode and later parameterize Availability Zone, VPC , Security ID values from the existing EC2 instance.
Parameters:
  ImageId:
    Description: WebServer EC2 instance typeProvide base AMI or Packer AMI reference
    Type: AWS::EC2::Image::Id
    Default: ami-0080e4c5bc078760e
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium	  
  AvailabilityZone:
    Description: WebServer EC2 AZ
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1b
    AllowedValues:
      - us-east-1a
      - us-east-1b
  KeyName:
    Description: Provide Existing key name.
    Type: AWS::EC2::KeyPair::KeyName
    Default: packer-infy-key
#  Tags: 
#    Type: String
#    Default: [Key: Name, Value: cf-stack-webserver1]
  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0bee687735f5ada3c
#    Default:
#      - sg-0bee687735f5ada3c
Resources:
  WebInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      KeyName: !Ref KeyName
      Tags:
        -
          Key: Name
          Value: cf-stack-webserver2	  
      SecurityGroupIds:
        - !Ref SecurityGroupIds
  MyLoadBalancerTest:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        - "us-east-1b"
      Instances:
        - Ref: WebInstance1
#        - Ref: logical name of AWS::EC2::Instance resource 2
      SecurityGroups:
        - sg-0201c59b31a0fa19b
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      HealthCheck:
          Target: HTTP:80/
          HealthyThreshold: '3'
          UnhealthyThreshold: '5'
          Interval: '30'
          Timeout: '5'
